apiVersion: v1
kind: Service
metadata:
  name: gitops-platform-service
  namespace: gitops-platform

spec:
  type: NodePort

  selector:
    app: gitops-platform

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080